### ISSUE TITLE
I have a question about the EventSource

### ISSUE THREAD

**Issue by ortegafernando** [jahid75/php-progress-bar-with-percentage#1]
Hi Niamul.

I have donwload the code and it works perfectly.

But I don't exactly understand one thing.

I see that app.js calls:

1. jQuery.ajax to begin the "long process" of writting data to a file
2. addEventListener to a new EventSource (stream.php)

What I dont' understand is this: usually, all EventSource events that I see are about calling a long process which sends message events to client.

But in your example, I don't see any loop in stream.php.

Why does stream.php send more than one message to the client?
Does jQuery.ajax "invoke" EventSource? 

Thanks a lot.

**Comment by jahid75** [comment]
@ortegafernando Thanks for reaching me.

If you see in the `app.js`, you can see with jQuery.ajax, we are just executing the query.php [here](https://github.com/jahid75/php-progress-bar-with-percentage/blob/4797e3f171bd82c18798b5501f72ee0e0cd8fa05/app.js#L11)
and while it'll run  it'll add the progress in a text file.
Then with the `stream.php` [here](https://github.com/jahid75/php-progress-bar-with-percentage/blob/4797e3f171bd82c18798b5501f72ee0e0cd8fa05/app.js#L12), we are just taking the text file contents. 

If you see the `file_processor.php` [here](https://github.com/jahid75/php-progress-bar-with-percentage/blob/4797e3f171bd82c18798b5501f72ee0e0cd8fa05/file_processor.php#L39), you'll get more ideas. 

Actually this is just a demo to get an idea about how to implement the progress bar with PHP.

Feel free to ask me if you need any other information. 
Happy Coding!

Thanks

**Comment by ortegafernando** [comment]
Thanks a lot.

What I don't understand is why this sentence

```
  var evSrc = new EventSource("stream.php?filename=" + fileName);
```
 is executing more than one time.

I see stream.php and I dont understand why it is executing several times (so it reports several: 
```
echo "data: {$status}\n\n";
```
Thanks

**Comment by jahid75** [comment]
We are using `EventSource` instance which is a web content's interface to [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events). If you take a look [here](https://developer.mozilla.org/en-US/docs/Web/API/EventSource), you'll get better idea about `EventSource`. 

Also, here is a great [answer about how the Server sent Events](https://stackoverflow.com/questions/7636165/how-do-server-sent-events-actually-work) work.

Hope you will get a better idea.

Thanks

**Comment by ortegafernando** [comment]
Hi, I have read before about sse.  As your link says "a long running http connection", I dont understand where is in your code the long running task.

I see app.js:
1. when I click on button, process starts eventStart() function.
2. eventStart function calls: query.php and stream.php as sse.
3. query.php is the long process function as it takes 100 seconds (it is an example, of course)
4. But what I don't understand is why stream.php that only reads one time the file, it keeps reading the file continuously or when it changes.

I thought that in this case, stream.php will be something similar like this (pseudo-code):

```
<?php
header('Content-Type: text/event-stream');
header('Cache-Control: no-cache');
require_once __DIR__ . '/file_processor.php';
$fileName = isset( $_GET['filename'] ) ? $_GET['filename'] : time();
$process = new FileProcessor($fileName);
$oldStatus = 0;
do {
   $status = $process->getText();
  if ($oldStatus != $status) {
      echo "data: {$status}\n\n";
  }
  $oldStatus = $status;
   //sleep
}
while ($status < 100);
echo "data: 100\n\n";  //just in case
$process->deleteFile();
```

Why your code in stream.php is being called again and again?

Thanks.

**Comment by jahid75** [comment]
Hi, as you can see on [this line ](https://github.com/jahid75/php-progress-bar-with-percentage/blob/4797e3f171bd82c18798b5501f72ee0e0cd8fa05/app.js#L17) the connection will close only if the status is `100`. 

So, when the `EventSource` is connected with the server, it's receiving the events from the server. Whenever something is happening on the server it's just sending that event to the front end. That's how it's working. 

Hope you now got the idea about how it's working under the hood. 

Thanks

**Comment by ortegafernando** [comment]
Sorry, I am a newbie and  I dont understand the logic.

I knew about the connection is open, until you want to close it, but I dont know why stream.php is "repeating" itselft. Does this 
```
var evSrc = new EventSource("stream.php?filename=" + fileName);
```
include someway of repeating "stream.php" until the connection is closed? 
I have always thought that you must have a loop (like my last post) in your event source.

It is my fault/mistake, but I dont understand.

**Comment by ortegafernando** [comment]
Hi, anyone? Thanks a lot.

**Comment by ortegafernando** [comment]
Hi, I think I have found the answer:

[https://stackoverflow.com/questions/53888030/why-do-server-sent-events-initiate-every-3-seconds/53889126](url)

[https://stackoverflow.com/questions/16315137/setting-time-interval-in-html5-server-sent-events](url)

THANKS A LOT !!!!!
